project:
  type: website
  output-dir: _site

website:
  title: "PageSieve Docs"
  favicon: "assets/logo.png"
  twitter-card: true
  open-graph:
    title: "PageSieve Docs"
    description: "Documentation website for PageSieve a browser extension that allows you to scrape websites without leaving your browser by defining CSS Selectors and XPath selectors."
  site-url: https://julius383.github.io/PageSieve/
  repo-url: https://github.com/julius383/PageSieve
  repo-actions: [edit, source, issue]
  navbar:
    tools:
        - icon: github
          menu:
            - text: Source Code
              href:  https://github.com/julius383/PageSieve
            - text: Report a Bug
              href:  https://github.com/julius383/PageSieve/issues
    left:
      - href: getting-started.qmd
        text: Getting Started
      - text: Examples
        href: examples/index.qmd
      - text: Changelog
        href: CHANGELOG.md
      - text: Roadmap
        href: roadmap.qmd
      - text: Reference
        menu:
          - href: architecture.qmd
            text: Architecture
          - href: reference/configuration.qmd
            text: Scrape Configuration
          - href: reference/extension-ui.qmd
            text: Extension UI Overview
          - href: reference/scraping-engine.qmd
            text: Scraping Engine Workflow
      - href: contributing.qmd
        text: Contributing

format:
  html:
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    syntax-highlighting: oblivion
