// Generated by CoffeeScript 2.7.0
/*
 The MIT License

 Copyright (c) 2012 Andrew Cantino
 Copyright (c) 2009 Andrew Cantino & Kyle Maxwell

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/
import DiffMatchPatch from '$lib/dmp.js';
import { finder } from '@medv/finder';

export class DomPredictionHelper {
    useAlternativeFinder: boolean;

    constructor() {
        this.useAlternativeFinder = false;
    }

    recursiveNodes(e: Node): Node[] {
        let n: Node[];
        if (e.nodeName && e.parentNode && e !== document.body) {
            n = this.recursiveNodes(e.parentNode);
        } else {
            n = [];
        }
        n.push(e);
        return n;
    }

    escapeCssNames(name: string): string {
        if (name) {
            try {
                return name
                    .replace(/\bselectorgadget_\w+\b/g, '')
                    .replace(/\\/g, '\\')
                    .replace(/[#;&,.+*~':"!^$[]()=>|\/]/g, (e: string) => {
                        return '\\' + e;
                    })
                    .replace(/\s+/, '');
            } catch (error) {
                console.log('exception in escapeCssNames');
                console.error(error);
                return '';
            }
        } else {
            return '';
        }
    }

    childElemNumber(elem: Element): number {
        let count: number;
        count = 0;
        let currentElement = elem;
        while (
            currentElement.previousSibling &&
            (currentElement = currentElement.previousSibling as Element)
        ) {
            if (currentElement.nodeType === 1) {
                count++;
            }
        }
        return count;
    }

    siblingsWithoutTextNodes(e: Element): Node[] {
        let node: Node;
        const nodes: NodeListOf<Node> = e.parentNode!.childNodes;
        const filtered_nodes: Node[] = [];
        for (let k = 0, len = nodes.length; k < len; k++) {
            node = nodes[k];
            if (node.nodeName.substring(0, 1) === '#') {
                continue;
            }
            if (node === e) {
                break;
            }
            filtered_nodes.push(node);
        }
        return filtered_nodes;
    }

    pathOf(elem: Element): string {
        let e: Node, j: number, k: number, len: number, path: string, siblings: Node[];
        path = '';
        const ref: Node[] = this.recursiveNodes(elem);
        for (k = 0, len = ref.length; k < len; k++) {
            e = ref[k];
            if (e) {
                siblings = this.siblingsWithoutTextNodes(e as Element);
                if ((e as Element).nodeName.toLowerCase() !== 'body') {
                    // Only look at 2 previous siblings.
                    j = siblings.length - 2 < 0 ? 0 : siblings.length - 2;
                    while (j < siblings.length) {
                        if (siblings[j] === e) {
                            break;
                        }
                        if (!(siblings[j] as Element).nodeName.match(/^(script|#.*?)$/i)) {
                            path +=
                                this.cssDescriptor(siblings[j] as Element) +
                                (j + 1 === siblings.length ? '+ ' : '~ ');
                        }
                        j++;
                    }
                }
                path += this.cssDescriptor(e as Element) + ' > ';
            }
        }
        return this.cleanCss(path);
    }

    pathOf2(elem: Element): string {
        return finder(elem, { root: document.body, timeoutMs: 1000 });
    }

    cssDescriptor(node: Element): string {
        let cssName: string, escaped: string, k: number, len: number, path: string, ref: string[];
        path = node.nodeName.toLowerCase();
        escaped = node.id && this.escapeCssNames(new String(node.id) as string);
        if (escaped && escaped.length > 0) {
            path += '#' + escaped;
        }
        if (node.className) {
            ref = node.className.split(' ');
            for (k = 0, len = ref.length; k < len; k++) {
                cssName = ref[k];
                escaped = this.escapeCssNames(cssName);
                if (cssName && escaped.length > 0) {
                    path += '.' + escaped;
                }
            }
        }
        if (node.nodeName.toLowerCase() !== 'body') {
            // nth-child needs to be last.
            path += ':nth-child(' + (this.childElemNumber(node) + 1) + ')';
        }
        return path;
    }

    cssDiff(array: string[]): string {
        // The library is imported, not assumed to be global
        const dmp = new DiffMatchPatch();

        let collective_common, diff;
        if (typeof array === 'undefined' || array.length === 0) {
            return '';
        }

        const existing_tokens = {};
        const encoded_css_array = this.encodeCssForDiff(array, existing_tokens);
        collective_common = encoded_css_array.pop();
        if (collective_common !== undefined) {
            for (const cssElem of encoded_css_array) {
                diff = dmp.diff_main(collective_common, cssElem);
                collective_common = '';
                for (const part of diff) {
                    if (part[0] === 0) {
                        collective_common += part[1];
                    }
                }
            }
            return this.decodeCss(collective_common, existing_tokens);
        }
        return '';
    }

    tokenizeCss(css_string: string): string[] {
        let skip: boolean, word: string;
        skip = false;
        word = '';
        const tokens = [];
        const ref = this.cleanCss(css_string);
        for (const char of ref) {
            if (skip) {
                skip = false;
            } else if (char === '\\') {
                skip = true;
            } else if (
                char === '.' ||
                char === ' ' ||
                char === '#' ||
                char === '>' ||
                char === ':' ||
                char === ',' ||
                char === '+' ||
                char === '~'
            ) {
                if (word.length > 0) {
                    tokens.push(word);
                }
                word = '';
            }
            word += char;
            if (char === ' ' || char === ',') {
                tokens.push(word);
                word = '';
            }
        }
        if (word.length > 0) {
            tokens.push(word);
        }
        return tokens;
    }

    // Same as tokenizeCss, except that siblings are treated as single tokens.
    tokenizeCssForDiff(css_string: string): string[] {
        let block: string[];
        let combined_tokens: string[] = [];
        block = [];
        const ref = this.tokenizeCss(css_string);
        for (const token of ref) {
            block.push(token);
            if (token === ' ' && block.length > 0) {
                combined_tokens = combined_tokens.concat(block);
                block = [];
            } else if (token === '+' || token === '~') {
                block = [block.join('')];
            }
        }
        if (block.length > 0) {
            return combined_tokens.concat(block);
        } else {
            return combined_tokens;
        }
    }

    decodeCss(aString: string, existing_tokens: { [key: string]: string }): string {
        let out: string;
        const inverted: { [key: string]: string } = this.invertObject(existing_tokens);
        out = '';
        const ref = aString.split('');
        for (const character of ref) {
            out += inverted[character];
        }
        return this.cleanCss(out);
    }

    // Encode css paths for diff using unicode codepoints to allow for a large number of tokens.
    encodeCssForDiff(strings: string[], existing_tokens: { [key: string]: string }): string[] {
        let out: string, ref: string[];
        let codepoint = 50;
        const strings_out: string[] = [];
        for (const aString of strings) {
            out = '';
            ref = this.tokenizeCssForDiff(aString);
            for (const token of ref) {
                if (!existing_tokens[token]) {
                    existing_tokens[token] = String.fromCharCode(codepoint++);
                }
                out += existing_tokens[token];
            }
            strings_out.push(out);
        }
        return strings_out;
    }

    tokenPriorities(tokens: string[]): number[] {
        let first: string, i: number, second: string;
        const epsilon = 0.001;
        const priorities: number[] = [];
        i = 0;
        for (const token of tokens) {
            first = token.substring(0, 1);
            second = token.substring(1, 2);
            if (first === ':' && second === 'n') {
                // :nth-child
                priorities[i] = 0;
            } else if (first === '>') {
                // >
                priorities[i] = 2;
            } else if (first === '+' || first === '~') {
                // + and ~
                priorities[i] = 3;
            } else if (
                first !== ':' &&
                first !== '.' &&
                first !== '#' &&
                first !== ' ' &&
                first !== '>' &&
                first !== '+' &&
                first !== '~'
            ) {
                // elem, etc.
                priorities[i] = 4;
            } else if (first === '.') {
                // classes
                priorities[i] = 5;
            } else if (first === '#') {
                // ids
                priorities[i] = 6;
                if (token.match(/\d{3,}/)) {
                    priorities[i] = 2.5;
                }
            } else {
                priorities[i] = 0;
            }
            priorities[i] += i * epsilon;
            i++;
        }
        return priorities;
    }

    orderFromPriorities(priorities: number[]): number[] {
        const tmp = [];
        const ordering = [];
        for (let i = 0; i < priorities.length; i++) {
            tmp[i] = {
                value: priorities[i],
                original: i,
            };
        }
        tmp.sort(function (a: { value: number }, b: { value: number }) {
            return a.value - b.value;
        });
        for (let i = 0; i < priorities.length; i++) {
            ordering[i] = tmp[i].original;
        }
        return ordering;
    }

    simplifyCss(css: string, selected: Element[], rejected: Element[]): string {
        let best_so_far: string, first: string, got_shorter: boolean, part: number;
        const parts = this.tokenizeCss(css);
        const priorities = this.tokenPriorities(parts);
        const ordering = this.orderFromPriorities(priorities);
        const selector = this.cleanCss(css);
        best_so_far = '';
        if (
            this.selectorGets('all', selected, selector) &&
            this.selectorGets('none', rejected, selector)
        ) {
            best_so_far = selector;
        }
        got_shorter = true;
        while (got_shorter) {
            got_shorter = false;
            for (let i = 0; i < parts.length; i++) {
                part = ordering[i];
                if (parts[part].length === 0) {
                    continue;
                }
                first = parts[part].substring(0, 1);
                if (first === ' ') {
                    continue;
                }
                if (this.wouldLeaveFreeFloatingNthChild(parts, part)) {
                    continue;
                }
                this._removeElements(part, parts, first, (selector: string) => {
                    if (
                        this.selectorGets('all', selected, selector) &&
                        this.selectorGets('none', rejected, selector) &&
                        (selector.length < best_so_far.length || best_so_far.length === 0)
                    ) {
                        best_so_far = selector;
                        got_shorter = true;
                        return true;
                    } else {
                        return false;
                    }
                });
            }
        }
        return this.cleanCss(best_so_far);
    }

    // Remove some elements depending on whether this is a sibling selector or not, and put them back if the block returns false.
    _removeElements(
        part: number,
        parts: string[],
        firstChar: string,
        callback: (selector: string) => boolean,
    ): string[] {
        let look_back_index: number;
        if (firstChar === '+' || firstChar === '~') {
            look_back_index = this.positionOfSpaceBeforeIndexOrLineStart(part, parts);
        } else {
            look_back_index = part;
        }
        const tmp = parts.slice(look_back_index, part + 1); // Save a copy of these parts.
        for (let j = look_back_index; j <= part; j++) {
            parts[j] = ''; // Clear it out.
        }
        const selector = this.cleanCss(parts.join(''));
        if (selector === '' || !callback(selector)) {
            for (let j = look_back_index; j <= part; j++) {
                parts[j] = tmp[j - look_back_index];
            }
        }
        return parts;
    }

    positionOfSpaceBeforeIndexOrLineStart(part: number, parts: string[]): number {
        let i: number;
        i = part;
        while (i >= 0 && parts[i] !== ' ') {
            i--;
        }
        if (i < 0) {
            i = 0;
        }
        return i;
    }

    // Has to handle parts with zero length.
    wouldLeaveFreeFloatingNthChild(parts: string[], part: number): boolean {
        let i: number, nth_child_is_on_right: boolean, space_is_on_left: boolean;
        space_is_on_left = nth_child_is_on_right = false;
        i = part + 1;
        while (i < parts.length && parts[i].length === 0) {
            i++;
        }
        if (i < parts.length && parts[i].substring(0, 2) === ':n') {
            nth_child_is_on_right = true;
        }
        i = part - 1;
        while (i > -1 && parts[i].length === 0) {
            i--;
        }
        if (i < 0 || parts[i] === ' ') {
            space_is_on_left = true;
        }
        return space_is_on_left && nth_child_is_on_right;
    }

    // Not intended for user CSS, does destructive sibling removal.  Expects strings to be escaped.
    cleanCss(css: string): string {
        let cleaned_css: string, last_cleaned_css: string | null;
        cleaned_css = css;
        last_cleaned_css = null;
        while (last_cleaned_css !== cleaned_css) {
            last_cleaned_css = cleaned_css;
            cleaned_css = cleaned_css
                .replace(/(^|\s+)(\+|~)/, '')
                .replace(/(\+|~)\s*$/, '')
                .replace(/>/g, ' > ')
                .replace(/\s*(>\s*)+/g, ' > ')
                .replace(/,/g, ' , ')
                .replace(/\s+/g, ' ')
                .replace(/^\s+|\s+$/g, '')
                .replace(/\s*,$/g, '')
                .replace(/^\s*,\s*/g, '')
                .replace(/\s*>$/g, '')
                .replace(/^>\s*/g, '')
                .replace(/[+~>]\s*,/g, ',')
                .replace(/[+~]\s*>/g, '>')
                .replace(/\s*(,\s*)+/g, ' , ');
        }
        return cleaned_css;
    }

    // Takes wrapped
    getPathsFor(nodeset: Element[]): string[] {
        let k: number, len: number, node: Element;
        const out = [];
        for (k = 0, len = nodeset.length; k < len; k++) {
            node = nodeset[k];
            if (node && node.nodeName) {
                out.push(!this.useAlternativeFinder ? this.pathOf(node) : this.pathOf2(node));
            }
        }
        return out;
    }

    // Takes wrapped
    predictCss(whitelist: Element[], blacklist: Element[], useAlternativeFinder: boolean | undefined = undefined): string {
        const currentFinder = this.useAlternativeFinder;
        this.useAlternativeFinder = useAlternativeFinder !== undefined ? useAlternativeFinder : currentFinder
        let union: string;
        if (whitelist.length === 0) {
            this.useAlternativeFinder = currentFinder;
            return '';
        }
        const selected_paths = this.getPathsFor(whitelist);
        const css = this.cssDiff(selected_paths);
        const simplest = this.simplifyCss(css, whitelist, blacklist);
        if (simplest.length > 0) {
            // Do we get off easy?
            this.useAlternativeFinder = currentFinder;
            return simplest;
        }
        // Okay, then make a union and possibly try to reduce subsets.
        union = '';
        for (const selected of whitelist) {
            // union = (this.pathOf(selected)) + ', ' + union;
            union = (!this.useAlternativeFinder ? this.pathOf(selected) : this.pathOf2(selected)) + ', ' + union;
        }
        union = this.cleanCss(union);
        this.useAlternativeFinder = currentFinder;
        return this.simplifyCss(union, whitelist, blacklist);
    }

    // Assumes list is jQuery node-set.  Todo: There is room for memoization here.
    selectorGets(type: 'all' | 'none', list: Element[], the_selector: string): boolean {
        if (list.length === 0) {
            return type === 'none';
        }

        try {
            if (type === 'all') {
                // "all": every element in the list must match the selector.
                return list.every((el) => el.matches(the_selector));
            } else {
                // "none"
                // "none": not a single element in the list can match the selector.
                return !list.some((el) => el.matches(the_selector));
            }
        } catch (e) {
            // A malformed selector will throw an error.
            console.log(`Error on selector: ${the_selector}`);
            console.error(e);
            return false; // Treat invalid selectors as non-matching
        }
    }

    invertObject<T extends Record<string, PropertyKey>>(obj: T): Record<T[keyof T], string> {
        const result: Record<PropertyKey, string> = {};
        for (const key in obj) {
            result[obj[key]] = key;
        }
        return result as Record<T[keyof T], string>;
    }

    cssToXPath(css_string: string): string {
        let css_block: string[], k: number, len: number, out: string, token: string;
        const tokens = this.tokenizeCss(css_string);
        if (tokens[0] && tokens[0] === ' ') {
            tokens.splice(0, 1);
        }
        if (tokens[tokens.length - 1] && tokens[tokens.length - 1] === ' ') {
            tokens.splice(tokens.length - 1, 1);
        }
        css_block = [];
        out = '';
        for (k = 0, len = tokens.length; k < len; k++) {
            token = tokens[k];
            if (token === ' ') {
                out += this.cssToXPathBlockHelper(css_block);
                css_block = [];
            } else {
                css_block.push(token);
            }
        }
        return out + this.cssToXPathBlockHelper(css_block);
    }

    // Process a block (html entity, class(es), id, :nth-child()) of css
    cssToXPathBlockHelper(css_block: string[]): string {
        let current: string,
            first: string,
            i: number,
            k: number,
            l: number,
            len: number,
            out: string,
            re: RegExpMatchArray | null,
            ref: number,
            rest: string;
        if (css_block.length === 0) {
            return '//';
        }
        out = '//';
        first = css_block[0].substring(0, 1);
        if (first === ',') {
            return ' | ';
        }
        if (first === ':' || first === '#' || first === '.') {
            out += '*';
        }
        const expressions = [];
        re = null;
        for (k = 0, len = css_block.length; k < len; k++) {
            current = css_block[k];
            first = current.substring(0, 1);
            rest = current.substring(1);
            if (first === ':') {
                // We only support :nth-child(n) at the moment.
                if ((re = rest.match(/^nth-child\((\d+)\)$/))) {
                    expressions.push(
                        '(((count(preceding-sibling::*) + 1) = ' + re[1] + ') and parent::*)',
                    );
                }
            } else if (first === '.') {
                expressions.push(
                    'contains(concat( " ", @class, " " ), concat( " ", \'' + rest + '\', " " ))',
                );
            } else if (first === '#') {
                expressions.push('(@id = "' + rest + '")');
            } else if (first === ',') {
            } else {
                out += current;
            }
        }
        if (expressions.length > 0) {
            out += '[';
        }
        for (
            i = l = 0, ref = expressions.length;
            0 <= ref ? l < ref : l > ref;
            i = 0 <= ref ? ++l : --l
        ) {
            out += expressions[i];
            if (i < expressions.length - 1) {
                out += ' and ';
            }
        }
        if (expressions.length > 0) {
            out += ']';
        }
        return out;
    }
}
